import { access, readFile, writeFile } from 'node:fs/promises';

// Embed the original WOFF2 files so both VS Code and exported HTML can
// render the theme without installing fonts or accessing a remote server.
const root = new URL('../', import.meta.url);
const fontRoot = new URL('../../fonts/', import.meta.url);
const missing = [];
for (const suffix of ['Rg', 'Bd', 'Eb']) {
  const name = `LINESeedJP_OTF_${suffix}.woff2`;
  try { await access(new URL(name, fontRoot)); }
  catch { missing.push(name); }
}
if (missing.length) {
  console.error(`LINE Seed JP fonts are missing: ${missing.join(', ')}\nDownload and extract LINE Seed JP from https://seed.line.me/index_jp.html\nThen run from the repository root:\n  node scripts/setup-fonts.mjs /path/to/LINESeedJP_20241105\nSee fonts/README.md for manual installation.`);
  process.exit(1);
}
const faces = await Promise.all(
  [['Rg', 400], ['Bd', 700], ['Eb', 800]].map(async ([suffix, weight]) => {
    const bytes = await readFile(new URL(`LINESeedJP_OTF_${suffix}.woff2`, fontRoot));
    return `@font-face { font-family: "LINE Seed JP"; font-style: normal; font-weight: ${weight}; font-display: block; src: url("data:font/woff2;base64,${bytes.toString('base64')}") format("woff2"); }`;
  }),
);
const styles = await readFile(new URL('themes/line-seed.source.css', root), 'utf8');
await writeFile(new URL('themes/line-seed.css', root),
  `/* @theme line-seed */\n/* Generated by npm run theme. Edit line-seed.source.css. */\n${faces.join('\n')}\n${styles}`);
console.log('Generated themes/line-seed.css with embedded LINE Seed JP fonts.');
